spring.application.name: student-service
spring:
    #Database Configurations
    datasource:
      url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

  # JPA Configuration
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect